"use client"
// Auto-generated by boneyard vite plugin — do not edit
import { registerBones } from 'boneyard-js/react'

import _landing_upcoming_race from './landing-upcoming-race.bones.json'
import _calendar_page from './calendar-page.bones.json'
import _next_race_card from './next-race-card.bones.json'
import _home_leaderboard_preview from './home-leaderboard-preview.bones.json'
import _home_performance_stats from './home-performance-stats.bones.json'
import _drivers_page from './drivers-page.bones.json'
import _groups_page from './groups-page.bones.json'
import _profile_page from './profile-page.bones.json'
import _prediction_form from './prediction-form.bones.json'
import _leaderboard_page from './leaderboard-page.bones.json'
import _group_detail_page from './group-detail-page.bones.json'

registerBones({
  "landing-upcoming-race": _landing_upcoming_race,
  "calendar-page": _calendar_page,
  "next-race-card": _next_race_card,
  "home-leaderboard-preview": _home_leaderboard_preview,
  "home-performance-stats": _home_performance_stats,
  "drivers-page": _drivers_page,
  "groups-page": _groups_page,
  "profile-page": _profile_page,
  "prediction-form": _prediction_form,
  "leaderboard-page": _leaderboard_page,
  "group-detail-page": _group_detail_page,
})
